version: "3.8"
services:
  nsub-api:
    build: .
    container_name: nsub_api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://nsub-postgres:5432/nsub
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      -   nsub-postgres

  nsub-postgres:
    image: postgres:16
    container_name: nsub_postgres
    environment:
      POSTGRES_DB: nsub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: